
name: Building AMI on Merge with Main

env:
  AWS_REGION: ${{secrets.AWS_REGION}}
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_AMI_USERS: ${{secrets.AWS_AMI_USERS}}
on:
  push:
    branches: [ main ]

jobs:
  ami_creation_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting up Hashicorp Packer
      uses: hashicorp-contrib/setup-packer@v1
      with:
        packer-version: 1.8.6

    - name: Setting packer logs to Verbose
      run: export PACKER_LOG=1

    - name: Download Packer plugin libraries
      run: packer init ami.pkr.hcl

    - name: Packer template validation
      run: packer validate ami.pkr.hcl

    - name: Building Packer Template
      run: packer build -var "region=${{secrets.AWS_REGION}}" -var "ami_users=${{secrets.AWS_AMI_USERS}}" ami.pkr.hcl 