
name: Building AMI on Merge with Main

env:
  AWS_REGION: ${{secrets.AWS_REGION}}
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_AMI_USERS: ${{secrets.AWS_AMI_USERS}}
on:
  push:
    branches: [ main ]

jobs:
  ami_creation_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting up Hashicorp Packer
      uses: hashicorp-contrib/setup-packer@v1
      with:
        packer-version: 1.8.6

    - name: Setting packer logs to Verbose
      run: export PACKER_LOG=1

    - name: Download Packer plugin libraries
      run: packer init ami.pkr.hcl

    - name: Packer template validation
      run: packer validate ami.pkr.hcl

    - name: Building Packer Template
      run: packer build -var "ami_users=${{env.AWS_AMI_USERS}}" ami.pkr.hcl 2>&1 | sudo tee output.txt; tail -2 output.txt | head -2 | awk 'match($0, /ami-.*/) { print substr($0, RSTART, RLENGTH) }' >> ami.txt

    - name: Create new launch template
      run: cat ami.txt | while read file; do aws ec2 create-launch-template-version --launch-template-name asg_launch_config --version-description latest --source-version 1 --launch-template-data "ImageId=$file"; done

    - name: Update the autoscaling group  
      run: aws autoscaling update-auto-scaling-group --auto-scaling-group-name $(aws autoscaling describe-auto-scaling-groups --query "AutoScalingGroups[?starts_with(AutoScalingGroupName,'terraform-')].AutoScalingGroupName" --output text) --launch-template LaunchTemplateName=asg_launch_config,Version='$Latest'

    - name: Instance refresh
      run: aws autoscaling start-instance-refresh --auto-scaling-group-name $(aws autoscaling describe-auto-scaling-groups --query "AutoScalingGroups[?starts_with(AutoScalingGroupName,'terraform-')].AutoScalingGroupName" --output text)